# Generated by Django 4.1.4 on 2022-12-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('profile_pic', models.ImageField(default="static 'img/user_default.jpg' ", upload_to='profile_pic/')),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='user', max_length=100)),
            ],
        ),
    ]
