# Generated by Django 4.1.4 on 2023-03-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_type', models.CharField(max_length=100)),
                ('w_name', models.CharField(max_length=100)),
                ('w_description', models.TextField(default='null')),
                ('w_difficulty', models.CharField(max_length=50)),
                ('w_muscles_targeted', models.CharField(max_length=100)),
                ('w_gif', models.ImageField(upload_to='workout_gifs/')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
