# Generated by Django 4.1.4 on 2023-06-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_blogmodel_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='trainer',
            new_name='user',
        ),
    ]
